/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddPageRequest {
  'page' : PageInput,
  'documentId' : DocumentId,
  'insertAtIndex' : [] | [bigint],
}
export interface CreateDocumentRequest {
  'name' : string,
  'pages' : Array<PageInput>,
}
export interface Document {
  'id' : DocumentId,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pages' : Array<Page>,
}
export type DocumentId = bigint;
export interface DocumentSummary {
  'id' : DocumentId,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pageCount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Page {
  'id' : PageId,
  'rotation' : PageRotation,
  'blob' : ExternalBlob,
  'ocrText' : [] | [string],
}
export type PageId = bigint;
export interface PageInput {
  'rotation' : PageRotation,
  'blob' : ExternalBlob,
  'ocrText' : [] | [string],
}
export type PageRotation = { 'deg0' : null } |
  { 'deg180' : null } |
  { 'deg270' : null } |
  { 'deg90' : null };
export interface ReorderPagesRequest {
  'pageIds' : Array<PageId>,
  'documentId' : DocumentId,
}
export interface RotatePageRequest {
  'rotation' : PageRotation,
  'documentId' : DocumentId,
  'pageId' : PageId,
}
export type Timestamp = bigint;
export interface UpdateDocumentNameRequest {
  'id' : DocumentId,
  'name' : string,
}
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addPage' : ActorMethod<[AddPageRequest], PageId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDocument' : ActorMethod<[CreateDocumentRequest], Document>,
  'deleteDocument' : ActorMethod<[DocumentId], undefined>,
  'deletePage' : ActorMethod<[DocumentId, PageId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[DocumentId], [] | [Document]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDocuments' : ActorMethod<[], Array<DocumentSummary>>,
  'reorderPages' : ActorMethod<[ReorderPagesRequest], undefined>,
  'rotatePage' : ActorMethod<[RotatePageRequest], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveOcrText' : ActorMethod<[DocumentId, PageId, string], undefined>,
  'searchDocuments' : ActorMethod<[string], Array<DocumentSummary>>,
  'updateDocumentName' : ActorMethod<[UpdateDocumentNameRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];