/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PageRotation = IDL.Variant({
  'deg0' : IDL.Null,
  'deg180' : IDL.Null,
  'deg270' : IDL.Null,
  'deg90' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PageInput = IDL.Record({
  'rotation' : PageRotation,
  'blob' : ExternalBlob,
  'ocrText' : IDL.Opt(IDL.Text),
});
export const DocumentId = IDL.Nat;
export const AddPageRequest = IDL.Record({
  'page' : PageInput,
  'documentId' : DocumentId,
  'insertAtIndex' : IDL.Opt(IDL.Nat),
});
export const PageId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateDocumentRequest = IDL.Record({
  'name' : IDL.Text,
  'pages' : IDL.Vec(PageInput),
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Page = IDL.Record({
  'id' : PageId,
  'rotation' : PageRotation,
  'blob' : ExternalBlob,
  'ocrText' : IDL.Opt(IDL.Text),
});
export const Document = IDL.Record({
  'id' : DocumentId,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pages' : IDL.Vec(Page),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DocumentSummary = IDL.Record({
  'id' : DocumentId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'pageCount' : IDL.Nat,
});
export const ReorderPagesRequest = IDL.Record({
  'pageIds' : IDL.Vec(PageId),
  'documentId' : DocumentId,
});
export const RotatePageRequest = IDL.Record({
  'rotation' : PageRotation,
  'documentId' : DocumentId,
  'pageId' : PageId,
});
export const UpdateDocumentNameRequest = IDL.Record({
  'id' : DocumentId,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addPage' : IDL.Func([AddPageRequest], [PageId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDocument' : IDL.Func([CreateDocumentRequest], [Document], []),
  'deleteDocument' : IDL.Func([DocumentId], [], []),
  'deletePage' : IDL.Func([DocumentId, PageId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([DocumentId], [IDL.Opt(Document)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDocuments' : IDL.Func([], [IDL.Vec(DocumentSummary)], ['query']),
  'reorderPages' : IDL.Func([ReorderPagesRequest], [], []),
  'rotatePage' : IDL.Func([RotatePageRequest], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveOcrText' : IDL.Func([DocumentId, PageId, IDL.Text], [], []),
  'searchDocuments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DocumentSummary)],
      ['query'],
    ),
  'updateDocumentName' : IDL.Func([UpdateDocumentNameRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PageRotation = IDL.Variant({
    'deg0' : IDL.Null,
    'deg180' : IDL.Null,
    'deg270' : IDL.Null,
    'deg90' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PageInput = IDL.Record({
    'rotation' : PageRotation,
    'blob' : ExternalBlob,
    'ocrText' : IDL.Opt(IDL.Text),
  });
  const DocumentId = IDL.Nat;
  const AddPageRequest = IDL.Record({
    'page' : PageInput,
    'documentId' : DocumentId,
    'insertAtIndex' : IDL.Opt(IDL.Nat),
  });
  const PageId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateDocumentRequest = IDL.Record({
    'name' : IDL.Text,
    'pages' : IDL.Vec(PageInput),
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Page = IDL.Record({
    'id' : PageId,
    'rotation' : PageRotation,
    'blob' : ExternalBlob,
    'ocrText' : IDL.Opt(IDL.Text),
  });
  const Document = IDL.Record({
    'id' : DocumentId,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'pages' : IDL.Vec(Page),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DocumentSummary = IDL.Record({
    'id' : DocumentId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'pageCount' : IDL.Nat,
  });
  const ReorderPagesRequest = IDL.Record({
    'pageIds' : IDL.Vec(PageId),
    'documentId' : DocumentId,
  });
  const RotatePageRequest = IDL.Record({
    'rotation' : PageRotation,
    'documentId' : DocumentId,
    'pageId' : PageId,
  });
  const UpdateDocumentNameRequest = IDL.Record({
    'id' : DocumentId,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addPage' : IDL.Func([AddPageRequest], [PageId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDocument' : IDL.Func([CreateDocumentRequest], [Document], []),
    'deleteDocument' : IDL.Func([DocumentId], [], []),
    'deletePage' : IDL.Func([DocumentId, PageId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([DocumentId], [IDL.Opt(Document)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDocuments' : IDL.Func([], [IDL.Vec(DocumentSummary)], ['query']),
    'reorderPages' : IDL.Func([ReorderPagesRequest], [], []),
    'rotatePage' : IDL.Func([RotatePageRequest], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveOcrText' : IDL.Func([DocumentId, PageId, IDL.Text], [], []),
    'searchDocuments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DocumentSummary)],
        ['query'],
      ),
    'updateDocumentName' : IDL.Func([UpdateDocumentNameRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };